# "test" suffix properties file. Scopes name samples: "test", "web-test", "api-test", etc.
# Overrides application.yml default properties
spring:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    db: malagolidb
    host: DB_MYSQL_DESAENV04_MALAGOLIDB_MALAGOLIDB_ENDPOINT
    username: malagolidb_WPROD
    password: DB_MYSQL_DESAENV04_MALAGOLIDB_MALAGOLIDB_WPROD



jwt:
  secret: ${SECRET_TOKEN}
  expiration: 86400000