# Properties file for local/dev environment
# You need to configure the environment variable in your IDE, more info in README.md
# Overrides application.yml default properties


spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:default
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
    platform: local
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
jwt:
  secret: ${SECRET_TOKEN}
  expiration: 86400000
